version: "3.7"
services: 
    api_service:
        build: .
        restart: always
        ports:
            - 8081:8081
        links:
            - mongo_db:app_db
    mongo_db:
        image: "mongo:4.4.3"
        restart: always
        ports:
            - 27017:27017

